import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils"; //this cn function combines functionality of twmerge and clsx

const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("antialiased font-sans", fontSans.variable)}>
        <nav>
          <h1>Recipes for Ninjas</h1>
        </nav>
        {children}
      </body>
    </html>
  );
}
